spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  data:
    redis:
      host: redis
      port: 6379


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

kafka:
  server: kafka:9092

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        sliding-window-type: count_based
        wait-duration-in-open-state:
          seconds: 1
        failure-rate-threshold: 50
  timelimiter:
    configs:
      default:
        timeout-duration:
          seconds: 4


management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin-server:9411/api/v2/spans
